# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/interchain_accounts/v1/account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.auth.v1beta1 import auth_pb2 as cosmos_dot_auth_dot_v1beta1_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ibc/applications/interchain_accounts/v1/account.proto',
  package='ibc.applications.interchain_accounts.v1',
  syntax='proto3',
  serialized_pb=_b('\n5ibc/applications/interchain_accounts/v1/account.proto\x12\'ibc.applications.interchain_accounts.v1\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/auth/v1beta1/auth.proto\"\xb9\x01\n\x11InterchainAccount\x12S\n\x0c\x62\x61se_account\x18\x01 \x01(\x0b\x32 .cosmos.auth.v1beta1.BaseAccountB\x1b\xd0\xde\x1f\x01\xf2\xde\x1f\x13yaml:\"base_account\"\x12/\n\raccount_owner\x18\x02 \x01(\tB\x18\xf2\xde\x1f\x14yaml:\"account_owner\":\x1e\x88\xa0\x1f\x00\x98\xa0\x1f\x00\xd2\xb4-\x12InterchainAccountIBGZEgithub.com/cosmos/ibc-go/v5/modules/apps/27-interchain-accounts/typesb\x06proto3')
  ,
  dependencies=[cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_auth_dot_v1beta1_dot_auth__pb2.DESCRIPTOR,])




_INTERCHAINACCOUNT = _descriptor.Descriptor(
  name='InterchainAccount',
  full_name='ibc.applications.interchain_accounts.v1.InterchainAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_account', full_name='ibc.applications.interchain_accounts.v1.InterchainAccount.base_account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\320\336\037\001\362\336\037\023yaml:\"base_account\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_owner', full_name='ibc.applications.interchain_accounts.v1.InterchainAccount.account_owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\024yaml:\"account_owner\"')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\210\240\037\000\230\240\037\000\322\264-\022InterchainAccountI')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=365,
)

_INTERCHAINACCOUNT.fields_by_name['base_account'].message_type = cosmos_dot_auth_dot_v1beta1_dot_auth__pb2._BASEACCOUNT
DESCRIPTOR.message_types_by_name['InterchainAccount'] = _INTERCHAINACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InterchainAccount = _reflection.GeneratedProtocolMessageType('InterchainAccount', (_message.Message,), dict(
  DESCRIPTOR = _INTERCHAINACCOUNT,
  __module__ = 'ibc.applications.interchain_accounts.v1.account_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.v1.InterchainAccount)
  ))
_sym_db.RegisterMessage(InterchainAccount)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('ZEgithub.com/cosmos/ibc-go/v5/modules/apps/27-interchain-accounts/types'))
_INTERCHAINACCOUNT.fields_by_name['base_account'].has_options = True
_INTERCHAINACCOUNT.fields_by_name['base_account']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\320\336\037\001\362\336\037\023yaml:\"base_account\"'))
_INTERCHAINACCOUNT.fields_by_name['account_owner'].has_options = True
_INTERCHAINACCOUNT.fields_by_name['account_owner']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\024yaml:\"account_owner\"'))
_INTERCHAINACCOUNT.has_options = True
_INTERCHAINACCOUNT._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\210\240\037\000\230\240\037\000\322\264-\022InterchainAccountI'))
# @@protoc_insertion_point(module_scope)
