# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lum-network/airdrop/claim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lum-network/airdrop/claim.proto',
  package='lum.network.airdrop',
  syntax='proto3',
  serialized_pb=_b('\n\x1flum-network/airdrop/claim.proto\x12\x13lum.network.airdrop\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\x80\x02\n\x0b\x43laimRecord\x12#\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x12\xf2\xde\x1f\x0eyaml:\"address\"\x12\x90\x01\n\x18initial_claimable_amount\x18\x02 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinBS\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\xc8\xde\x1f\x00\xf2\xde\x1f\x1fyaml:\"initial_claimable_amount\"\x12\x39\n\x10\x61\x63tion_completed\x18\x03 \x03(\x08\x42\x1f\xf2\xde\x1f\x17yaml:\"action_completed\"\xc8\xde\x1f\x00*7\n\x06\x41\x63tion\x12\x0e\n\nActionVote\x10\x00\x12\x17\n\x13\x41\x63tionDelegateStake\x10\x01\x1a\x04\x88\xa3\x1e\x00\x42.Z,github.com/lum-network/chain/x/airdrop/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,])

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='lum.network.airdrop.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ActionVote', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ActionDelegateStake', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000')),
  serialized_start=369,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
ActionVote = 0
ActionDelegateStake = 1



_CLAIMRECORD = _descriptor.Descriptor(
  name='ClaimRecord',
  full_name='lum.network.airdrop.ClaimRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='lum.network.airdrop.ClaimRecord.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\016yaml:\"address\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_claimable_amount', full_name='lum.network.airdrop.ClaimRecord.initial_claimable_amount', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\310\336\037\000\362\336\037\037yaml:\"initial_claimable_amount\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_completed', full_name='lum.network.airdrop.ClaimRecord.action_completed', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\027yaml:\"action_completed\"\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=367,
)

_CLAIMRECORD.fields_by_name['initial_claimable_amount'].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
DESCRIPTOR.message_types_by_name['ClaimRecord'] = _CLAIMRECORD
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClaimRecord = _reflection.GeneratedProtocolMessageType('ClaimRecord', (_message.Message,), dict(
  DESCRIPTOR = _CLAIMRECORD,
  __module__ = 'lum_network.airdrop.claim_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.airdrop.ClaimRecord)
  ))
_sym_db.RegisterMessage(ClaimRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/lum-network/chain/x/airdrop/types'))
_ACTION.has_options = True
_ACTION._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000'))
_CLAIMRECORD.fields_by_name['address'].has_options = True
_CLAIMRECORD.fields_by_name['address']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\016yaml:\"address\"'))
_CLAIMRECORD.fields_by_name['initial_claimable_amount'].has_options = True
_CLAIMRECORD.fields_by_name['initial_claimable_amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\310\336\037\000\362\336\037\037yaml:\"initial_claimable_amount\"'))
_CLAIMRECORD.fields_by_name['action_completed'].has_options = True
_CLAIMRECORD.fields_by_name['action_completed']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\027yaml:\"action_completed\"\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
