# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v1/genesis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ibc.core.client.v1 import client_pb2 as ibc_dot_core_dot_client_dot_v1_dot_client__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ibc/core/client/v1/genesis.proto',
  package='ibc.core.client.v1',
  syntax='proto3',
  serialized_pb=_b('\n ibc/core/client/v1/genesis.proto\x12\x12ibc.core.client.v1\x1a\x1fibc/core/client/v1/client.proto\x1a\x14gogoproto/gogo.proto\"\xff\x03\n\x0cGenesisState\x12Z\n\x07\x63lients\x18\x01 \x03(\x0b\x32).ibc.core.client.v1.IdentifiedClientStateB\x1e\xc8\xde\x1f\x00\xaa\xdf\x1f\x16IdentifiedClientStates\x12\x80\x01\n\x11\x63lients_consensus\x18\x02 \x03(\x0b\x32).ibc.core.client.v1.ClientConsensusStatesB:\xc8\xde\x1f\x00\xaa\xdf\x1f\x16\x43lientsConsensusStates\xf2\xde\x1f\x18yaml:\"clients_consensus\"\x12h\n\x10\x63lients_metadata\x18\x03 \x03(\x0b\x32-.ibc.core.client.v1.IdentifiedGenesisMetadataB\x1f\xc8\xde\x1f\x00\xf2\xde\x1f\x17yaml:\"clients_metadata\"\x12\x30\n\x06params\x18\x04 \x01(\x0b\x32\x1a.ibc.core.client.v1.ParamsB\x04\xc8\xde\x1f\x00\x12\x35\n\x10\x63reate_localhost\x18\x05 \x01(\x08\x42\x1b\xf2\xde\x1f\x17yaml:\"create_localhost\"\x12=\n\x14next_client_sequence\x18\x06 \x01(\x04\x42\x1f\xf2\xde\x1f\x1byaml:\"next_client_sequence\"\"3\n\x0fGenesisMetadata\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c:\x04\x88\xa0\x1f\x00\"\xa2\x01\n\x19IdentifiedGenesisMetadata\x12\'\n\tclient_id\x18\x01 \x01(\tB\x14\xf2\xde\x1f\x10yaml:\"client_id\"\x12\\\n\x0f\x63lient_metadata\x18\x02 \x03(\x0b\x32#.ibc.core.client.v1.GenesisMetadataB\x1e\xc8\xde\x1f\x00\xf2\xde\x1f\x16yaml:\"client_metadata\"B:Z8github.com/cosmos/ibc-go/v5/modules/core/02-client/typesb\x06proto3')
  ,
  dependencies=[ibc_dot_core_dot_client_dot_v1_dot_client__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='ibc.core.client.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clients', full_name='ibc.core.client.v1.GenesisState.clients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\252\337\037\026IdentifiedClientStates')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clients_consensus', full_name='ibc.core.client.v1.GenesisState.clients_consensus', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\252\337\037\026ClientsConsensusStates\362\336\037\030yaml:\"clients_consensus\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clients_metadata', full_name='ibc.core.client.v1.GenesisState.clients_metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\362\336\037\027yaml:\"clients_metadata\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='ibc.core.client.v1.GenesisState.params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_localhost', full_name='ibc.core.client.v1.GenesisState.create_localhost', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\027yaml:\"create_localhost\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_client_sequence', full_name='ibc.core.client.v1.GenesisState.next_client_sequence', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\033yaml:\"next_client_sequence\"')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=623,
)


_GENESISMETADATA = _descriptor.Descriptor(
  name='GenesisMetadata',
  full_name='ibc.core.client.v1.GenesisMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ibc.core.client.v1.GenesisMetadata.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ibc.core.client.v1.GenesisMetadata.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\210\240\037\000')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=676,
)


_IDENTIFIEDGENESISMETADATA = _descriptor.Descriptor(
  name='IdentifiedGenesisMetadata',
  full_name='ibc.core.client.v1.IdentifiedGenesisMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ibc.core.client.v1.IdentifiedGenesisMetadata.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\020yaml:\"client_id\"')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_metadata', full_name='ibc.core.client.v1.IdentifiedGenesisMetadata.client_metadata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\362\336\037\026yaml:\"client_metadata\"')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=841,
)

_GENESISSTATE.fields_by_name['clients'].message_type = ibc_dot_core_dot_client_dot_v1_dot_client__pb2._IDENTIFIEDCLIENTSTATE
_GENESISSTATE.fields_by_name['clients_consensus'].message_type = ibc_dot_core_dot_client_dot_v1_dot_client__pb2._CLIENTCONSENSUSSTATES
_GENESISSTATE.fields_by_name['clients_metadata'].message_type = _IDENTIFIEDGENESISMETADATA
_GENESISSTATE.fields_by_name['params'].message_type = ibc_dot_core_dot_client_dot_v1_dot_client__pb2._PARAMS
_IDENTIFIEDGENESISMETADATA.fields_by_name['client_metadata'].message_type = _GENESISMETADATA
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['GenesisMetadata'] = _GENESISMETADATA
DESCRIPTOR.message_types_by_name['IdentifiedGenesisMetadata'] = _IDENTIFIEDGENESISMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATE,
  __module__ = 'ibc.core.client.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.GenesisState)
  ))
_sym_db.RegisterMessage(GenesisState)

GenesisMetadata = _reflection.GeneratedProtocolMessageType('GenesisMetadata', (_message.Message,), dict(
  DESCRIPTOR = _GENESISMETADATA,
  __module__ = 'ibc.core.client.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.GenesisMetadata)
  ))
_sym_db.RegisterMessage(GenesisMetadata)

IdentifiedGenesisMetadata = _reflection.GeneratedProtocolMessageType('IdentifiedGenesisMetadata', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFIEDGENESISMETADATA,
  __module__ = 'ibc.core.client.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.IdentifiedGenesisMetadata)
  ))
_sym_db.RegisterMessage(IdentifiedGenesisMetadata)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z8github.com/cosmos/ibc-go/v5/modules/core/02-client/types'))
_GENESISSTATE.fields_by_name['clients'].has_options = True
_GENESISSTATE.fields_by_name['clients']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\252\337\037\026IdentifiedClientStates'))
_GENESISSTATE.fields_by_name['clients_consensus'].has_options = True
_GENESISSTATE.fields_by_name['clients_consensus']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\252\337\037\026ClientsConsensusStates\362\336\037\030yaml:\"clients_consensus\"'))
_GENESISSTATE.fields_by_name['clients_metadata'].has_options = True
_GENESISSTATE.fields_by_name['clients_metadata']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\362\336\037\027yaml:\"clients_metadata\"'))
_GENESISSTATE.fields_by_name['params'].has_options = True
_GENESISSTATE.fields_by_name['params']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['create_localhost'].has_options = True
_GENESISSTATE.fields_by_name['create_localhost']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\027yaml:\"create_localhost\"'))
_GENESISSTATE.fields_by_name['next_client_sequence'].has_options = True
_GENESISSTATE.fields_by_name['next_client_sequence']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\033yaml:\"next_client_sequence\"'))
_GENESISMETADATA.has_options = True
_GENESISMETADATA._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\210\240\037\000'))
_IDENTIFIEDGENESISMETADATA.fields_by_name['client_id'].has_options = True
_IDENTIFIEDGENESISMETADATA.fields_by_name['client_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\362\336\037\020yaml:\"client_id\"'))
_IDENTIFIEDGENESISMETADATA.fields_by_name['client_metadata'].has_options = True
_IDENTIFIEDGENESISMETADATA.fields_by_name['client_metadata']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000\362\336\037\026yaml:\"client_metadata\"'))
# @@protoc_insertion_point(module_scope)
