# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lum-network/millions/callbacks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lum-network/millions/callbacks.proto',
  package='lum.network.millions',
  syntax='proto3',
  serialized_pb=_b('\n$lum-network/millions/callbacks.proto\x12\x14lum.network.millions\x1a\x14gogoproto/gogo.proto\"l\n\x0fSplitDelegation\x12\x19\n\x11validator_address\x18\x01 \x01(\t\x12>\n\x06\x61mount\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\"y\n\x10\x44\x65legateCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x12\n\ndeposit_id\x18\x02 \x01(\x04\x12@\n\x11split_delegations\x18\x03 \x03(\x0b\x32%.lum.network.millions.SplitDelegation\"~\n\x12UndelegateCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x15\n\rwithdrawal_id\x18\x02 \x01(\x04\x12@\n\x11split_delegations\x18\x03 \x03(\x0b\x32%.lum.network.millions.SplitDelegation\"f\n\x12RedelegateCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12?\n\x10split_delegation\x18\x02 \x01(\x0b\x32%.lum.network.millions.SplitDelegation\"8\n\x14\x43laimRewardsCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x64raw_id\x18\x02 \x01(\x04\"?\n\x18TransferToNativeCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x12\n\ndeposit_id\x18\x02 \x01(\x04\"\x87\x01\n\x1aTransferFromNativeCallback\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".lum.network.millions.TransferType\x12\x0f\n\x07pool_id\x18\x02 \x01(\x04\x12\x0f\n\x07\x64raw_id\x18\x03 \x01(\x04\x12\x15\n\rwithdrawal_id\x18\x04 \x01(\x04\"-\n\x1aSetWithdrawAddressCallback\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04*\x92\x01\n\x0cTransferType\x12.\n\x19TRANSFER_TYPE_UNSPECIFIED\x10\x00\x1a\x0f\x8a\x9d \x0bUnspecified\x12\"\n\x13TRANSFER_TYPE_CLAIM\x10\x01\x1a\t\x8a\x9d \x05\x43laim\x12(\n\x16TRANSFER_TYPE_WITHDRAW\x10\x02\x1a\x0c\x8a\x9d \x08Withdraw\x1a\x04\x88\xa3\x1e\x01\x42/Z-github.com/lum-network/chain/x/millions/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])

_TRANSFERTYPE = _descriptor.EnumDescriptor(
  name='TransferType',
  full_name='lum.network.millions.TransferType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSFER_TYPE_UNSPECIFIED', index=0, number=0,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \013Unspecified')),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSFER_TYPE_CLAIM', index=1, number=1,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \005Claim')),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSFER_TYPE_WITHDRAW', index=2, number=2,
      options=_descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \010Withdraw')),
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\001')),
  serialized_start=858,
  serialized_end=1004,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERTYPE)

TransferType = enum_type_wrapper.EnumTypeWrapper(_TRANSFERTYPE)
TRANSFER_TYPE_UNSPECIFIED = 0
TRANSFER_TYPE_CLAIM = 1
TRANSFER_TYPE_WITHDRAW = 2



_SPLITDELEGATION = _descriptor.Descriptor(
  name='SplitDelegation',
  full_name='lum.network.millions.SplitDelegation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator_address', full_name='lum.network.millions.SplitDelegation.validator_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='lum.network.millions.SplitDelegation.amount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=192,
)


_DELEGATECALLBACK = _descriptor.Descriptor(
  name='DelegateCallback',
  full_name='lum.network.millions.DelegateCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.DelegateCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit_id', full_name='lum.network.millions.DelegateCallback.deposit_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='split_delegations', full_name='lum.network.millions.DelegateCallback.split_delegations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=315,
)


_UNDELEGATECALLBACK = _descriptor.Descriptor(
  name='UndelegateCallback',
  full_name='lum.network.millions.UndelegateCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.UndelegateCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdrawal_id', full_name='lum.network.millions.UndelegateCallback.withdrawal_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='split_delegations', full_name='lum.network.millions.UndelegateCallback.split_delegations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=443,
)


_REDELEGATECALLBACK = _descriptor.Descriptor(
  name='RedelegateCallback',
  full_name='lum.network.millions.RedelegateCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.RedelegateCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='split_delegation', full_name='lum.network.millions.RedelegateCallback.split_delegation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=547,
)


_CLAIMREWARDSCALLBACK = _descriptor.Descriptor(
  name='ClaimRewardsCallback',
  full_name='lum.network.millions.ClaimRewardsCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.ClaimRewardsCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='draw_id', full_name='lum.network.millions.ClaimRewardsCallback.draw_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=605,
)


_TRANSFERTONATIVECALLBACK = _descriptor.Descriptor(
  name='TransferToNativeCallback',
  full_name='lum.network.millions.TransferToNativeCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.TransferToNativeCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit_id', full_name='lum.network.millions.TransferToNativeCallback.deposit_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=670,
)


_TRANSFERFROMNATIVECALLBACK = _descriptor.Descriptor(
  name='TransferFromNativeCallback',
  full_name='lum.network.millions.TransferFromNativeCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='lum.network.millions.TransferFromNativeCallback.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.TransferFromNativeCallback.pool_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='draw_id', full_name='lum.network.millions.TransferFromNativeCallback.draw_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdrawal_id', full_name='lum.network.millions.TransferFromNativeCallback.withdrawal_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=673,
  serialized_end=808,
)


_SETWITHDRAWADDRESSCALLBACK = _descriptor.Descriptor(
  name='SetWithdrawAddressCallback',
  full_name='lum.network.millions.SetWithdrawAddressCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='lum.network.millions.SetWithdrawAddressCallback.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=855,
)

_DELEGATECALLBACK.fields_by_name['split_delegations'].message_type = _SPLITDELEGATION
_UNDELEGATECALLBACK.fields_by_name['split_delegations'].message_type = _SPLITDELEGATION
_REDELEGATECALLBACK.fields_by_name['split_delegation'].message_type = _SPLITDELEGATION
_TRANSFERFROMNATIVECALLBACK.fields_by_name['type'].enum_type = _TRANSFERTYPE
DESCRIPTOR.message_types_by_name['SplitDelegation'] = _SPLITDELEGATION
DESCRIPTOR.message_types_by_name['DelegateCallback'] = _DELEGATECALLBACK
DESCRIPTOR.message_types_by_name['UndelegateCallback'] = _UNDELEGATECALLBACK
DESCRIPTOR.message_types_by_name['RedelegateCallback'] = _REDELEGATECALLBACK
DESCRIPTOR.message_types_by_name['ClaimRewardsCallback'] = _CLAIMREWARDSCALLBACK
DESCRIPTOR.message_types_by_name['TransferToNativeCallback'] = _TRANSFERTONATIVECALLBACK
DESCRIPTOR.message_types_by_name['TransferFromNativeCallback'] = _TRANSFERFROMNATIVECALLBACK
DESCRIPTOR.message_types_by_name['SetWithdrawAddressCallback'] = _SETWITHDRAWADDRESSCALLBACK
DESCRIPTOR.enum_types_by_name['TransferType'] = _TRANSFERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SplitDelegation = _reflection.GeneratedProtocolMessageType('SplitDelegation', (_message.Message,), dict(
  DESCRIPTOR = _SPLITDELEGATION,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.SplitDelegation)
  ))
_sym_db.RegisterMessage(SplitDelegation)

DelegateCallback = _reflection.GeneratedProtocolMessageType('DelegateCallback', (_message.Message,), dict(
  DESCRIPTOR = _DELEGATECALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.DelegateCallback)
  ))
_sym_db.RegisterMessage(DelegateCallback)

UndelegateCallback = _reflection.GeneratedProtocolMessageType('UndelegateCallback', (_message.Message,), dict(
  DESCRIPTOR = _UNDELEGATECALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.UndelegateCallback)
  ))
_sym_db.RegisterMessage(UndelegateCallback)

RedelegateCallback = _reflection.GeneratedProtocolMessageType('RedelegateCallback', (_message.Message,), dict(
  DESCRIPTOR = _REDELEGATECALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.RedelegateCallback)
  ))
_sym_db.RegisterMessage(RedelegateCallback)

ClaimRewardsCallback = _reflection.GeneratedProtocolMessageType('ClaimRewardsCallback', (_message.Message,), dict(
  DESCRIPTOR = _CLAIMREWARDSCALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.ClaimRewardsCallback)
  ))
_sym_db.RegisterMessage(ClaimRewardsCallback)

TransferToNativeCallback = _reflection.GeneratedProtocolMessageType('TransferToNativeCallback', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERTONATIVECALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.TransferToNativeCallback)
  ))
_sym_db.RegisterMessage(TransferToNativeCallback)

TransferFromNativeCallback = _reflection.GeneratedProtocolMessageType('TransferFromNativeCallback', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERFROMNATIVECALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.TransferFromNativeCallback)
  ))
_sym_db.RegisterMessage(TransferFromNativeCallback)

SetWithdrawAddressCallback = _reflection.GeneratedProtocolMessageType('SetWithdrawAddressCallback', (_message.Message,), dict(
  DESCRIPTOR = _SETWITHDRAWADDRESSCALLBACK,
  __module__ = 'lum_network.millions.callbacks_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.SetWithdrawAddressCallback)
  ))
_sym_db.RegisterMessage(SetWithdrawAddressCallback)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-github.com/lum-network/chain/x/millions/types'))
_TRANSFERTYPE.has_options = True
_TRANSFERTYPE._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\001'))
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_UNSPECIFIED"].has_options = True
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_UNSPECIFIED"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \013Unspecified'))
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_CLAIM"].has_options = True
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_CLAIM"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \005Claim'))
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_WITHDRAW"].has_options = True
_TRANSFERTYPE.values_by_name["TRANSFER_TYPE_WITHDRAW"]._options = _descriptor._ParseOptions(descriptor_pb2.EnumValueOptions(), _b('\212\235 \010Withdraw'))
_SPLITDELEGATION.fields_by_name['amount'].has_options = True
_SPLITDELEGATION.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
