# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/crypto/keyring/v1/record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cosmos.crypto.hd.v1 import hd_pb2 as cosmos_dot_crypto_dot_hd_dot_v1_dot_hd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/crypto/keyring/v1/record.proto',
  package='cosmos.crypto.keyring.v1',
  syntax='proto3',
  serialized_pb=_b('\n%cosmos/crypto/keyring/v1/record.proto\x12\x18\x63osmos.crypto.keyring.v1\x1a\x14gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a\x1c\x63osmos/crypto/hd/v1/hd.proto\"\xae\x03\n\x06Record\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x07pub_key\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x37\n\x05local\x18\x03 \x01(\x0b\x32&.cosmos.crypto.keyring.v1.Record.LocalH\x00\x12\x39\n\x06ledger\x18\x04 \x01(\x0b\x32\'.cosmos.crypto.keyring.v1.Record.LedgerH\x00\x12\x37\n\x05multi\x18\x05 \x01(\x0b\x32&.cosmos.crypto.keyring.v1.Record.MultiH\x00\x12;\n\x07offline\x18\x06 \x01(\x0b\x32(.cosmos.crypto.keyring.v1.Record.OfflineH\x00\x1a/\n\x05Local\x12&\n\x08priv_key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x1a\x38\n\x06Ledger\x12.\n\x04path\x18\x01 \x01(\x0b\x32 .cosmos.crypto.hd.v1.BIP44Params\x1a\x07\n\x05Multi\x1a\t\n\x07OfflineB\x06\n\x04itemB1Z+github.com/cosmos/cosmos-sdk/crypto/keyring\xc8\xe1\x1e\x00\x62\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,cosmos_dot_crypto_dot_hd_dot_v1_dot_hd__pb2.DESCRIPTOR,])




_RECORD_LOCAL = _descriptor.Descriptor(
  name='Local',
  full_name='cosmos.crypto.keyring.v1.Record.Local',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priv_key', full_name='cosmos.crypto.keyring.v1.Record.Local.priv_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=491,
)

_RECORD_LEDGER = _descriptor.Descriptor(
  name='Ledger',
  full_name='cosmos.crypto.keyring.v1.Record.Ledger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='cosmos.crypto.keyring.v1.Record.Ledger.path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=549,
)

_RECORD_MULTI = _descriptor.Descriptor(
  name='Multi',
  full_name='cosmos.crypto.keyring.v1.Record.Multi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=558,
)

_RECORD_OFFLINE = _descriptor.Descriptor(
  name='Offline',
  full_name='cosmos.crypto.keyring.v1.Record.Offline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=569,
)

_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='cosmos.crypto.keyring.v1.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cosmos.crypto.keyring.v1.Record.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='cosmos.crypto.keyring.v1.Record.pub_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local', full_name='cosmos.crypto.keyring.v1.Record.local', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ledger', full_name='cosmos.crypto.keyring.v1.Record.ledger', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multi', full_name='cosmos.crypto.keyring.v1.Record.multi', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offline', full_name='cosmos.crypto.keyring.v1.Record.offline', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RECORD_LOCAL, _RECORD_LEDGER, _RECORD_MULTI, _RECORD_OFFLINE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='cosmos.crypto.keyring.v1.Record.item',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=147,
  serialized_end=577,
)

_RECORD_LOCAL.fields_by_name['priv_key'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RECORD_LOCAL.containing_type = _RECORD
_RECORD_LEDGER.fields_by_name['path'].message_type = cosmos_dot_crypto_dot_hd_dot_v1_dot_hd__pb2._BIP44PARAMS
_RECORD_LEDGER.containing_type = _RECORD
_RECORD_MULTI.containing_type = _RECORD
_RECORD_OFFLINE.containing_type = _RECORD
_RECORD.fields_by_name['pub_key'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RECORD.fields_by_name['local'].message_type = _RECORD_LOCAL
_RECORD.fields_by_name['ledger'].message_type = _RECORD_LEDGER
_RECORD.fields_by_name['multi'].message_type = _RECORD_MULTI
_RECORD.fields_by_name['offline'].message_type = _RECORD_OFFLINE
_RECORD.oneofs_by_name['item'].fields.append(
  _RECORD.fields_by_name['local'])
_RECORD.fields_by_name['local'].containing_oneof = _RECORD.oneofs_by_name['item']
_RECORD.oneofs_by_name['item'].fields.append(
  _RECORD.fields_by_name['ledger'])
_RECORD.fields_by_name['ledger'].containing_oneof = _RECORD.oneofs_by_name['item']
_RECORD.oneofs_by_name['item'].fields.append(
  _RECORD.fields_by_name['multi'])
_RECORD.fields_by_name['multi'].containing_oneof = _RECORD.oneofs_by_name['item']
_RECORD.oneofs_by_name['item'].fields.append(
  _RECORD.fields_by_name['offline'])
_RECORD.fields_by_name['offline'].containing_oneof = _RECORD.oneofs_by_name['item']
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(

  Local = _reflection.GeneratedProtocolMessageType('Local', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_LOCAL,
    __module__ = 'cosmos.crypto.keyring.v1.record_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.crypto.keyring.v1.Record.Local)
    ))
  ,

  Ledger = _reflection.GeneratedProtocolMessageType('Ledger', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_LEDGER,
    __module__ = 'cosmos.crypto.keyring.v1.record_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.crypto.keyring.v1.Record.Ledger)
    ))
  ,

  Multi = _reflection.GeneratedProtocolMessageType('Multi', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_MULTI,
    __module__ = 'cosmos.crypto.keyring.v1.record_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.crypto.keyring.v1.Record.Multi)
    ))
  ,

  Offline = _reflection.GeneratedProtocolMessageType('Offline', (_message.Message,), dict(
    DESCRIPTOR = _RECORD_OFFLINE,
    __module__ = 'cosmos.crypto.keyring.v1.record_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.crypto.keyring.v1.Record.Offline)
    ))
  ,
  DESCRIPTOR = _RECORD,
  __module__ = 'cosmos.crypto.keyring.v1.record_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.crypto.keyring.v1.Record)
  ))
_sym_db.RegisterMessage(Record)
_sym_db.RegisterMessage(Record.Local)
_sym_db.RegisterMessage(Record.Ledger)
_sym_db.RegisterMessage(Record.Multi)
_sym_db.RegisterMessage(Record.Offline)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z+github.com/cosmos/cosmos-sdk/crypto/keyring\310\341\036\000'))
# @@protoc_insertion_point(module_scope)
