# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/slashing/v1beta1/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/slashing/v1beta1/tx.proto',
  package='cosmos.slashing.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n cosmos/slashing/v1beta1/tx.proto\x12\x17\x63osmos.slashing.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\"e\n\tMsgUnjail\x12;\n\x0evalidator_addr\x18\x01 \x01(\tB#\xd2\xb4-\x14\x63osmos.AddressString\xea\xde\x1f\x07\x61\x64\x64ress:\x1b\x82\xe7\xb0*\x0evalidator_addr\x88\xa0\x1f\x00\x98\xa0\x1f\x01\"\x13\n\x11MsgUnjailResponse2_\n\x03Msg\x12X\n\x06Unjail\x12\".cosmos.slashing.v1beta1.MsgUnjail\x1a*.cosmos.slashing.v1beta1.MsgUnjailResponseB3Z-github.com/cosmos/cosmos-sdk/x/slashing/types\xa8\xe2\x1e\x01\x62\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,cosmos_dot_msg_dot_v1_dot_msg__pb2.DESCRIPTOR,])




_MSGUNJAIL = _descriptor.Descriptor(
  name='MsgUnjail',
  full_name='cosmos.slashing.v1beta1.MsgUnjail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator_addr', full_name='cosmos.slashing.v1beta1.MsgUnjail.validator_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\322\264-\024cosmos.AddressString\352\336\037\007address')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\347\260*\016validator_addr\210\240\037\000\230\240\037\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=236,
)


_MSGUNJAILRESPONSE = _descriptor.Descriptor(
  name='MsgUnjailResponse',
  full_name='cosmos.slashing.v1beta1.MsgUnjailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=257,
)

DESCRIPTOR.message_types_by_name['MsgUnjail'] = _MSGUNJAIL
DESCRIPTOR.message_types_by_name['MsgUnjailResponse'] = _MSGUNJAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgUnjail = _reflection.GeneratedProtocolMessageType('MsgUnjail', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNJAIL,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjail)
  ))
_sym_db.RegisterMessage(MsgUnjail)

MsgUnjailResponse = _reflection.GeneratedProtocolMessageType('MsgUnjailResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNJAILRESPONSE,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjailResponse)
  ))
_sym_db.RegisterMessage(MsgUnjailResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-github.com/cosmos/cosmos-sdk/x/slashing/types\250\342\036\001'))
_MSGUNJAIL.fields_by_name['validator_addr'].has_options = True
_MSGUNJAIL.fields_by_name['validator_addr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\322\264-\024cosmos.AddressString\352\336\037\007address'))
_MSGUNJAIL.has_options = True
_MSGUNJAIL._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\347\260*\016validator_addr\210\240\037\000\230\240\037\001'))

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='cosmos.slashing.v1beta1.Msg',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=259,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='Unjail',
    full_name='cosmos.slashing.v1beta1.Msg.Unjail',
    index=0,
    containing_service=None,
    input_type=_MSGUNJAIL,
    output_type=_MSGUNJAILRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
