# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lum-network/millions/prize_ref.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lum-network/millions/prize_ref.proto',
  package='lum.network.millions',
  syntax='proto3',
  serialized_pb=_b('\n$lum-network/millions/prize_ref.proto\x12\x14lum.network.millions\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\x98\x01\n\x08PrizeRef\x12>\n\x06\x61mount\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\x16\n\x08prize_id\x18\x02 \x01(\x04\x42\x04\xc8\xde\x1f\x01\x12\x34\n\x0ewinner_address\x18\x03 \x01(\tB\x1c\xc8\xde\x1f\x01\xd2\xb4-\x14\x63osmos.AddressStringB/Z-github.com/lum-network/chain/x/millions/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,])




_PRIZEREF = _descriptor.Descriptor(
  name='PrizeRef',
  full_name='lum.network.millions.PrizeRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='lum.network.millions.PrizeRef.amount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prize_id', full_name='lum.network.millions.PrizeRef.prize_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winner_address', full_name='lum.network.millions.PrizeRef.winner_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\001\322\264-\024cosmos.AddressString')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['PrizeRef'] = _PRIZEREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrizeRef = _reflection.GeneratedProtocolMessageType('PrizeRef', (_message.Message,), dict(
  DESCRIPTOR = _PRIZEREF,
  __module__ = 'lum_network.millions.prize_ref_pb2'
  # @@protoc_insertion_point(class_scope:lum.network.millions.PrizeRef)
  ))
_sym_db.RegisterMessage(PrizeRef)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-github.com/lum-network/chain/x/millions/types'))
_PRIZEREF.fields_by_name['amount'].has_options = True
_PRIZEREF.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'))
_PRIZEREF.fields_by_name['prize_id'].has_options = True
_PRIZEREF.fields_by_name['prize_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\001'))
_PRIZEREF.fields_by_name['winner_address'].has_options = True
_PRIZEREF.fields_by_name['winner_address']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\001\322\264-\024cosmos.AddressString'))
# @@protoc_insertion_point(module_scope)
